"""
GitHub Trending Report - Generated by HAJIMI on 2026-07-08
============================================================
Task: Open GitHub Trending Python, extract top 3 projects, write markdown report.
"""

REPORT_MD = """# GitHub Python Trending Top 3

> Generated by HAJIMI AI Agent on 2026-07-08
> Source: https://github.com/trending/python?since=daily

---

"""

# The agent will fill in the rest from the snapshot data
print(REPORT_MD)
