"""Layout tokens — sizes, spacing, animation. No color values."""

# Panel dimensions (--panel-width, --drawer-w, --radius)
PANEL_WIDTH = 480
PANEL_HEIGHT = 520
COMPACT_WIDTH = 320
COMPACT_HEIGHT = 52
DRAWER_WIDTH = 168
RADIUS = 16
RADIUS_SM = 10
RADIUS_COMPACT = 26
COMPACT_PILL_RADIUS = 999
COMPACT_RECT_RADIUS = 16
COMPACT_MIN_W = 320
COMPACT_MIN_H = 48
COMPACT_MAX_W = 420
COMPACT_MAX_H = 96
MEDIUM_MIN_W = 360
MEDIUM_MIN_H = 300

# Typography (HTML body / view-medium — sizes only)
FONT_FAMILY = "Segoe UI"
FONT_FAMILY_FALLBACK = "Microsoft YaHei UI"
FONT_SIZE_BASE = 13
FONT_SIZE_CHAT = 13
FONT_SIZE_CAPTION = 11
FONT_SIZE_TITLE = 13
LINE_HEIGHT = 1.5
CONTENT_PAD_H = 16
CONTENT_PAD_V = 12
CONTENT_PAD_BOTTOM = 14
TOP_BAR_MIN_H = 64
TOP_BAR_MAX_H = 80
TOP_BAR_PAD_H = 24
TOP_BAR_PAD_V = 12
TOP_BAR_SPACING = 16
TOP_BAR_TITLE_GAP = 4
INPUT_DOCK_PAD = 12
BUBBLE_MAX_RATIO = 0.85

# Animation (--ease-out-cubic)
ANIM_DRAWER_MS = 200
ANIM_SWITCH_MS = 250
ANIM_COMPACT_RESIZE_MS = 120
EASING_OUT_CUBIC = (0.33, 1.0, 0.68, 1.0)
